# -*- coding: utf-8 -*-
"""Copy of task 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vjrDl5kDiqIhj6w-lwalLeSVsFxRmOqD

### 1-Write a Python program that takes two numbers as user input and performs addition on them.
"""

def adding(x,y):
  return x+y
x, y = map(int, input().split())
print(adding(x,y))

"""### 2-Write a Python program that takes an integer as input and checks if it is even or odd. Print "Even" if the number is divisible by 2, otherwise print "Odd"."""

def isEven_isOdd(x):
  if x%2==0:
    print("Even")
  else:
    print("Odd")
x= int (input())
isEven_isOdd(x)

"""### 3-Write a Python program that prints all the even numbers from 1 to 20 using a for loop"""

for i in range(1,21):
  if i%2==0:
    print(i)

"""### 4-Write a Python function that takes a string as input and counts the number of vowels (a, e, i, o, u) in the string. The function should return the count"""

def count_vowels(s):
  v=['a','e','i','o','u']
  counter=0
  for i in range(len(s)):
    if s[i] in v:
      counter+=1
  return counter
x=input()
count_vowels(x)

"""### 5-Write a Python program that creates a list of numbers from 1 to 10. Use a loop to iterate over the list and print each number of power 2."""

s=[]
for i in range(1,11):
  s.append(i)
s_square=[]
for i in s:
  s_square.append(i**2)
s_square

"""### 6-Write a Python program that calculates the average grade for a student based on their scores in different subjects. The program should include the following steps:

#### 1-Create variables to store the student's name, subject names, and corresponding scores. Initialize the variables with sample data.

#### 2-Prompt the user to enter the student's name and assign it to the name variable.

#### 3-Use a loop to prompt the user to enter the subject names and corresponding scores. Store the subject names in a list and the scores in another list.

#### 4-After collecting the scores, calculate the average grade by summing up all the scores and dividing by the total number of subjects.

#### 5-Check if the average grade is above a 70, print a congratulatory message. Otherwise, print an encouragement message.
"""

def grade(x):
  s=input('inter the student name please: ')
  grades=[]
  c_name=[]
  semestar={}
  for _ in range (x):
    c=input('coures name: ')
    c_name.append(c)
    g=float(input('the grade for this  coures: '))
    grades.append(g)
  sum=0
  ave=0
  for i in range(x):
    semestar[c_name[i]]=grades[i]
    sum+=grades[i]
  ave=sum/len(grades)
  if ave>70:
    return 'Congratulation' ,  ave ,semestar
  else:
    return 'Unfortunately' ,  ave , semestar

x=int(input('enter the numbers of courses: '))
grade(x)



"""### 7-Find Common Elements
### Write a Python function that takes two lists as input and returns a new list containing the common elements present in both lists.
"""

def commen_e(list1,list2):
  list3=[]
  for i in list1:
    if i in list2:
      list3.append(i)
  return list3
list1=[1,2,3,4,5,'o',0.67,'da']
list2=[3,4,5,6,7,0.67,'o']
commen_e(list1,list2)

"""### 8-Write a Python function that takes a list of numbers and an element to remove from the list."""

def remove(list1,x):
  for i in list1:
    if i==x:
      list1.remove(i)
  return list1
remove(['A',1,'7',8,3.14,'o'],8)

"""### 9-Given 4 numbers A, B, C and D. Print the last 2 digits from their Multiplication.
### Example :
### the Multiplication of 4 numbers is 5 * 7 * 2 * 4 = 280 so the answer will be the last 2 digits which are 80.
"""

def last_2(A,B,C,D):
  m=A*B*C*D
  return m%100
last_2(16,7,6,9)

"""### 10- Given a number X. Determine if the number is prime or not"""

def is_prime(X):
  for i in range(2,X):
    if X/i==0:
      return False
  return True
is_prime(17)

"""### 11- Given a number N and a list A of N numbers. Determine if the number X exists in array A or not and print its position (0-index)."""

def is_exis(N,A,X):
  for i in range(N): # 0 1 2 3 4
    if A[i]==X:
      return i
  else:
    return 'Not exist'
is_exis(5,[1,2,3,4,5],1)

"""### 12- Given a number N and a list A of N numbers. Determine if the array is lucky or not.

#### Note: the array is lucky if the frequency (number of occurrence) of the minimum element is odd.
"""

def is_lucky(N,A):
  min=float('inf')
  for i in range(N):
    if A[i]<min:
      min=A[i]
  exist=0
  for i in range(N):
    if A[i]==min:
      exist+=1
  if exist%2==1:
    return 'Lucky'
  else:
    return 'Not lucy'
is_lucky(8,[99,65,11,29,34,22,55,11])

"""### 13-Given a number N and a list A of N numbers. Print the array after doing the following operations:

#### Find minimum number in these numbers.
#### Find maximum number in these numbers.
##### Swap minimum number with maximum number.
"""

def swap(N,A):
  min=float('inf')
  indx_min=0
  max=float('-inf')
  indx_max=0
  for i in range(N):
    if A[i]<min:
      min=A[i]
      indx_min=i
    if A[i]>max:
      max=A[i]
      indx_max=i
  A[indx_min]=max
  A[indx_max]=min
  return A , max , min
swap(8,[1,2,3,4,5,6,7,8])

"""### 14-Given a number N and an array A of N numbers. Print the lowest number and its position.

### Note: if there are more than one answer print first one's position.
"""

def lowest(N,A):
  min=float('inf')
  indx_min=0
  for i in range(N):
    if A[i]<min:
      min=A[i]
      indx_min=i
  return min , indx_min
lowest(6,[7,3,0,3,7,2])

"""### 15-Given a number N and an array A of N numbers. Print the numbers after sorting them"""

def sort(list1):

  for i in range (len(list1)-1,-1,-1): # 5 4 3 2 1 0

    max=float('-inf')

    indx_max=0

    for j in range(i,-1,-1):# (5,4,3,2,1,0) (4,3,2,1,0) (3,2,1,0) (2,1,0) (1,0) (0)

      if list1[j]> max:

        max=list1[j]

        indx_max=j

    list1[indx_max]=list1[i]

    list1[i]=max

  return list1

sort([7,3,0,3,7,2])
sort([9,5,3,1,6,2,8,3,6,4,0])
#selection sort او insertion sort  XDمش فاكر بقي انا مسوبط اني لسا فاكر الكود اساسا

"""### 16- Write a Python program to remove spaces from a given string"""

def remove_s(x):
  x=x.replace(' ','')
  return x
x='Shady                                               mayez'
remove_s(x)

"""### 17-write a Python program to swap first and last element of any list."""

def alist(l):
  temp=l[0]
  l[0]=l[-1]
  l[-1]=temp
  return l
alist([0,4,2,5,3,5,3,4,10])

"""# **Write a Python Program to Find HCF.**
## Highest Common Factor(HCF): HCF, or Highest Common Factor, is the largest positive integer that divides two or more numbers without leaving a remainder. Formula: For two numbers a and b, the HCF can be found using the formula:

** HCF(𝑎, 𝑏) = GCD(𝑎, 𝑏)**
For more than two numbers, you can find the HCF by taking the GCD of pairs of numbers at a time until you reach the last pair.

# **Note: GCD stands for Greatest Common Divisor, use function.**

"""

def gcd(x,y):
  while x != y:
    if x>y:
      x=x-y
    elif y>x:
      y=y-x
  else:
    return x
gcd(48,18)

